name: E2E Tests

on:
  workflow_dispatch:
  schedule:
      - cron: '35 13 * * *' # Runs at 1:02 PM daily (13:20 in 24-hour format)
  pull_request:
      branches: [ main ]

jobs:
  windows-edge:
    runs-on: windows-latest

    steps:
       - name: Checkout Code
         uses: actions/checkout@v4

       - name: Setup JDK 21
         uses: actions/setup-java@v4
         with:
           distribution: 'zulu'
           java-version: '21'

       - name: Setup Maven 
         uses: stCarolas/setup-maven@v4.5
         with:
           maven-version: 3.9.9

       - name: Run Tests
         continue-on-error: true
         run: mvn test "-DbrowserType=edge" "-Dallure.results.directory=target/allure-results" "-DheadlessExecution=true" "-Dtest=${{ github.event.inputs.testsPath }}"

       - name: Generate Allure Report Single File
         continue-on-error: true
         run:  mvn allure:report

       - name: Upload Allure Report as Artifact
         uses: actions/upload-artifact@v3
         with:
          name: Edge_Windows_Allure
          path: target/site/allure-maven-plugin/index.html

       - name: Publish Report
         continue-on-error: true
         uses: dorny/test-reporter@v1
         if: success() || failure()
         with:
          name: Tests Report Edge_Windows
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit

  ubuntu-chrome:
      runs-on: ubuntu-latest

      steps:
       - name: Checkout Code
         uses: actions/checkout@v4

       - name: Setup JDK 21
         uses: actions/setup-java@v4
         with:
           distribution: 'zulu'
           java-version: '21'

       - name: Setup Maven 
         uses: stCarolas/setup-maven@v4.5
         with:
           maven-version: 3.9.9

       - name: Run Tests
         continue-on-error: true
         run: mvn test "-DbrowserType=chrome" "-Dallure.results.directory=target/allure-results" "-DheadlessExecution=true" "-Dtest=${{ github.event.inputs.testsPath }}"

       - name: Generate Allure Report Single File
         continue-on-error: true
         run:  mvn allure:report

       - name: Upload Allure Report as Artifact
         uses: actions/upload-artifact@v3
         with:
          name: Edge_Windows_Allure
          path: target/site/allure-maven-plugin/index.html

       - name: Publish Report
         continue-on-error: true
         uses: dorny/test-reporter@v1
         if: success() || failure()
         with:
          name: Tests Report Edge_Windows
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit
    
  
